chat/urls.py
from django.urls import path
from chat.views import GroupListView, GroupDetailView

app_name = 'chat'
urlpatterns = [
    path('groups/', GroupListView.as_view(), name='group_list'),
    path('group/<uuid:uuid>/', GroupDetailView.as_view(), name='group_detail'),
]

config/urls.py
from django.conf.urls import handler403, handler404

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

handler403 = 'vcars.views.custom_403'
handler404 = 'vcars.views.custom_404'
handler500 = 'vcars.views.custom_500'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vcars.urls', namespace='vcars')),
    path('api/', include('vcars_api.urls', namespace='api_vcars')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('chat/', include('chat.urls')),
    path('', include('game.urls', namespace='game')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]

game/urls.py
from django.urls import path
from game.views import GameView, RecordView

app_name = 'game'
urlpatterns = [
    path('game/', GameView.as_view(), name='game'),
    path('save-record/', RecordView.as_view(), name='save_record')
]

game/models.py
from django.db import models
from django.contrib.auth.models import User


class Record(models.Model):
    record = models.PositiveIntegerField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.record)

    class Meta:
        ordering = ['-record']

game/views.py
from django.http import HttpResponseBadRequest
from django.shortcuts import render
from django.views.generic import ListView, View

from game.models import Record


class GameView(ListView):
    template_name = 'game/game.html'
    model = Record
    context_object_name = 'records'


class RecordView(View):
    def post(self, request, *args, **kwargs):
        score = int(request.POST.get('score'))
        if score and request.user.is_authenticated:
            all_records = Record.objects.all()
            owner = request.user
            records = all_records.filter(owner=owner)
            if records.exists():
                record = records.first()
                best_owner_score = record.record
                if score > best_owner_score:
                    record.record = score
                    record.save()
            else:
                all_records.create(owner=owner, record=score)
            return render(request, 'includes/records.html', {'records': all_records})
        return HttpResponseBadRequest()

templates/game/game.html
<html lang="ru">
{% load static %}
<head>
    <title>mcqueen racing</title>
    <link rel="stylesheet" href="{% static 'css/game_style.css' %}">
</head>
<body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
<div class="road"></div>
<img src='{% static 'images/car.png' %}' class="car">
<img src='{% static 'images/bsh.png' %}' class='bush bush1'>
<img src='{% static 'images/bsh.png' %}' class='bush bush2'>
<img src='{% static 'images/bsh.png' %}' class='bush bush3'>
<img src='{% static 'images/bsh.png' %}' class='bush bush4'>
<img src='{% static 'images/bsh.png' %}' class='bush bush5'>
<img src='{% static 'images/bsh.png' %}' class='bush bush6'>
<img src='{% static 'images/bush.png' %}' class='bush bush7'>
<img src='{% static 'images/bush.png' %}' class='bush bush8'>
<img src='{% static 'images/mountain1.png' %}' class='mountain mountain1'>
<img src='{% static 'images/mountain2.png' %}' class='mountain mountain2'>
<img src='{% static 'images/mountain1.png' %}' class='mountain mountain3'>
<img src='{% static 'images/mountain2.png' %}' class='mountain mountain4'>
<img src='{% static 'images/arrow.png' %}' class='arrow'>
<img src='{% static 'images/detour.png' %}' class='danger'>
<img src='{% static  'images/coin.png' %}' class='coin'>

<button type="button" class="game-button">
    <img src='{% static 'images/pause.png' %}' class="pause"/>
    <img src='{% static 'images/play.png' %}' class="play"/>
</button>
<div class="game-score">
    0
</div>
<div class="backdrop">
    <div class="container">
        <p class="finish-text">Итоговый счет: <span class="finish-text-score">0</span></p>
        <button type="button" class="restart-button">Начать сначала</button>
        <button type="button" class="go-to-index-button"><a href="/">Вернуться на главную</a></button>
        <button type="button" class="view-records-button">Посмотреть рекорды</button>
    </div>
</div>
<form
        id="save-record-form"
        hx-post="{% url 'game:save_record' %}"
        hx-target=".records"
        hx-trigger="submit"
        hx-swap="outerHTML"
        style="display: none;">
    <input type="hidden" name="score" id="score-input">
</form>
<div class="modal" style="display: none;">
    <div class="modal-content">
        <h2>Рекорды игры</h2>
        <div class="records">
            {% include 'includes/records.html' %}
        </div>
        <button type="button" class="close-modal">Закрыть</button>
    </div>
</div>
<audio id="cars-soundtrack" style="display: none" loop>
  <source src="{% static 'soundtrack/cars_soundtrack.mp3' %}" type="audio/mpeg" />
  <p>
    Ваш браузер не поддерживает HTML5 аудио
  </p>
</audio>
<script src="https://unpkg.com/htmx.org@1.9.4"></script>
<script src={% static 'scripts/constants.js' %}></script>
<script src={% static 'scripts/movement.js' %}></script>
<script src={% static 'scripts/utils.js' %}></script>
<script src={% static 'scripts/spritesAnimation.js' %}></script>
<script src={% static 'scripts/elementAnimation.js' %}></script>
<script src={% static 'scripts/main.js' %}></script>

</body>
</html>