chat/urls.py
from django.urls import path
from chat.views import GroupListView, GroupDetailView

app_name = 'chat'
urlpatterns = [
    path('groups/', GroupListView.as_view(), name='group_list'),
    path('group/<uuid:uuid>/', GroupDetailView.as_view(), name='group_detail'),
]

config/urls.py
from django.conf.urls import handler403, handler404

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

handler403 = 'vcars.views.custom_403'
handler404 = 'vcars.views.custom_404'
handler500 = 'vcars.views.custom_500'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vcars.urls', namespace='vcars')),
    path('api/', include('vcars_api.urls', namespace='api_vcars')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('chat/', include('chat.urls')),
    path('', include('game.urls', namespace='game')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]

game/urls.py
from django.urls import path
from game.views import GameView, RecordView

app_name = 'game'
urlpatterns = [
    path('game/', GameView.as_view(), name='game'),
    path('save-record/', RecordView.as_view(), name='save_record')
]

vcars/urls.py
from django.conf.urls.static import static
from django.urls import path
from django.views.generic import TemplateView

from config import settings
from . import views
from .views import LikeView

app_name = 'vcars'
urlpatterns = [
    path('', views.PictureListView.as_view(), name='index'),
    path('tag/<slug:tag_slug>/', views.PictureListView.as_view(), name='tagged_index'),
    path('pic/<slug:slug>/', views.PicDetailView.as_view(), name='pic_detail'),
    path('addpic/', views.CreatePic.as_view(), name='post_pic'),
    path('rating/', LikeView.as_view(), name='rating'),

]

vcars/models.py
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager
from PIL import Image

from services.utils import unique_slugify


class PicManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().prefetch_related('tags')


class Pic(models.Model):
    tags = TaggableManager()
    name = models.CharField(max_length=25)
    body = models.TextField()
    pic = models.ImageField(upload_to='images',
                            validators=[FileExtensionValidator(allowed_extensions=['jpg', 'webp', 'jpeg', 'png'])])
    thumb = models.CharField(max_length=120, null=True, blank=True)
    creation_time = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=255, blank=True)
    objects = models.Manager()
    custom = PicManager()

    class Meta:
        ordering = ['-creation_time']
        indexes = [models.Index(fields=['-creation_time'])]

    def get_absolute_url(self):
        return reverse('vcars:pic_detail', args=[self.slug])

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = unique_slugify(self, self.name)
        super().save(*args, **kwargs)
        img = Image.open(self.pic.path)
        if img.height > 320 or img.width > 320:
            img.thumbnail((320, 320))
            thumb = f'media/thumbs/{self.id}.{img.format}'

            img.save(thumb)
            Pic.objects.filter(id=self.id).update(thumb=thumb)

    def count_rating(self):
        return sum([rating.rating for rating in self.ratings.all()])

    def __str__(self):
        return self.name


class Comment(models.Model):
    pic = models.ForeignKey(Pic, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=64)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created']
        indexes = [models.Index(fields=['created'])]


class Rating(models.Model):
    pic = models.ForeignKey(Pic, on_delete=models.CASCADE, related_name='ratings')
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    rating = models.IntegerField(choices=[(1, 'Нравится'), (2, 'Не нравится')])
    created = models.DateTimeField(auto_now_add=True)
    ip = models.GenericIPAddressField()

    class Meta:
        unique_together = ('pic', 'ip')
        ordering = ('-created',)
        indexes = [models.Index(fields=['created', 'rating'])]

vcars/forms.py
from django import forms
from taggit.forms import TagField
from .models import Comment, Pic


class CommentForm(forms.ModelForm):
    name = forms.CharField(label='Имя', widget=forms.TextInput(attrs={"class": "form-control mb-1", }))
    body = forms.CharField(label='Комментарий', widget=forms.Textarea(attrs={"class": "form-control mb-1", }))

    class Meta:
        model = Comment
        fields = ['name', 'body']


class PicForm(forms.ModelForm):
    tags = TagField(label='Тэги', required=True,
                           widget=forms.TextInput(attrs={"class": "form-control", 'placeholder': 'Тэги через запятую'}))
    name = forms.CharField(label='Название', required=True,
                           widget=forms.TextInput(attrs={"class": "form-control"}))
    pic = forms.ImageField(label='Картинка', required=True, widget=forms.FileInput(
        attrs={'class': 'form-control', 'id': 'customFile'}
    ))
    body = forms.CharField(label='Описание', required=True,
                           widget=forms.Textarea(attrs={"class": "form-control",
                                                        'placeholder': 'Напишите что нибудь интересное о вашей картинке'}))

    class Meta:
        model = Pic
        fields = ['tags', 'name', 'pic', 'body']

vcars/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import ListView, DetailView, CreateView, View
from django.http import JsonResponse, HttpResponseBadRequest
from django.core.exceptions import MultipleObjectsReturned
from django.shortcuts import render, get_object_or_404
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.core.cache import cache
from rest_framework.reverse import reverse_lazy
from taggit.models import Tag
from vcars.models import Pic, Comment, Rating
from vcars.forms import CommentForm, PicForm


class PictureListView(ListView):
    model = Pic
    template_name = 'vcars/list_pics.html'
    paginate_by = 6
    context_object_name = 'pics'
    queryset = Pic.custom.all()

    def get_queryset(self):
        queryset = cache.get_or_set('cached_pics_list', super().get_queryset())
        tag_slug = self.kwargs.get('tag_slug', None)
        if tag_slug:
            try:
                tag = get_object_or_404(Tag, slug=tag_slug)
                queryset = queryset.filter(tags__in=[tag])
            except MultipleObjectsReturned:
                pass
        if 'query' in self.request.GET:
            query = self.request.GET.get('query')
            search_query = SearchQuery(query)
            search_vector = SearchVector('name', 'body', 'tags')
            queryset = queryset.annotate(search=search_vector, rank=SearchRank(search_vector, search_query)).filter(
                search=query)
            self.kwargs['query'] = query
        return queryset


class PicDetailView(DetailView):
    model = Pic
    template_name = 'vcars/pic_detail.html'
    context_object_name = 'pic'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = Comment.objects.filter(pic=self.object)
        return context

    def get(self, request, *args, **kwargs):
        initial = {}
        if request.user.is_authenticated:
            initial = {'name': request.user.username}
        self.extra_context = {'form': CommentForm(initial=initial)}
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = CommentForm(data=request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.pic = self.object
            comment.save()
            return render(request, 'includes/comment.html', context={'comment': comment})
        return HttpResponseBadRequest()


class CreatePic(SuccessMessageMixin, CreateView):
    form_class = PicForm
    template_name = 'vcars/post_pic.html'
    success_message = 'Картинка успешно добавлена!'

    def get_success_url(self):
        return reverse_lazy('vcars:pic_detail', kwargs={'slug': self.object.slug})

    def form_valid(self, form):
        cache.delete('cached_pics_list')
        return super().form_valid(form)


class LikeView(View):
    model = Rating

    def post(self, request, *args, **kwargs):
        pic_id = self.request.POST.get('pic_id')
        val = int(request.POST.get('value'))
        ip = request.META.get('HTTP_X_FORWARDED_FOR') if request.META.get('HTTP_X_FORWARDED_FOR') else request.META.get(
            'REMOTE_ADDR')
        user = request.user if request.user.is_authenticated else None
        rating, created = self.model.objects.get_or_create(
            pic_id=pic_id,
            ip=ip,
            defaults={'rating': val, 'user': user}
        )
        if not created:
            if rating.rating == val:
                rating.delete()
            else:
                rating.rating = val
                rating.user = user
                rating.save()
        return JsonResponse({'rating_sum': rating.pic.count_rating()})


def custom_404(request, exception):
    return render(request, 'errors/custom_error.html', status=404,
                  context={'error_msg': 'К сожалению данная страница не была найдена'})


def custom_500(request):
    return render(request, 'errors/custom_error.html', status=500,
                  context={'error_msg': 'Внутрення ошибка сервера, мы уже работает над исправлением'})


def custom_403(request, exception):
    return render(request, 'errors/custom_error.html', status=403,
                  context={'error_msg': 'Доступ к этой странице запрещен'})

templates/vcars/base.html
{% load static %}
{% load django_bootstrap5 %}
{% load cache %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link href="{% static 'css/vcars.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/chat.css' %}" rel="stylesheet" type="text/css"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>

</head>
<body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
<nav class="navbar navbar-expand-lg bg-light">
    {% cache 600 header %}
        <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'vcars:index' %}">
            <img src="{% static 'images/icon.png' %}" alt="Logo" width="30" height="24"
                 class="d-inline-block align-text-top">
            Tachki
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="/">Картинки</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href={% url 'chat:group_list' %}>Список чатов</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href={% url 'game:game' %}>Играть</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'vcars:post_pic' %}">Добавить картинку</a>
                </li>

            </ul>

        </div>
    {% endcache %}
    {% if user.is_authenticated %}
        <span class="login">Hi, <a class='text-decoration-none'
                                   href="{{ user.profile.get_absolute_url }}">{{ user.username }}</a></span>
        <form class="logout-form" action="{% url 'logout' %}" method="post">
            {% csrf_token %}
            <a class="text-decoration-none" href="#" onclick="parentNode.submit();">Log Out</a>
        </form>
    {% else %}
        <span class="login">You are not <a href="{% url 'login' %}"
                                           class="text-decoration-none">logged in</a></span>
    {% endif %}
    <form class="d-flex" id="search-form" role="search" method="GET">
        <input id="search-input" class="form-control me-2" type="search" placeholder="Поиск картинки"
               aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
    </form>

    </div>

</nav>
<main>

    <script src="https://unpkg.com/htmx.org@1.9.4"></script>
    <script src="{% static 'scripts/searchhook.js' %}"></script>
    {% block content %}

    {% endblock %}

</main>

<footer class="bg-body-tertiary text-center text-lg-start">

    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05);">
        © 2024 Copyright
    </div>

</footer>
</body>
</html>

templates/vcars/list_pics.html
{% extends 'vcars/base.html' %}
{% block content %}
    {% load static %}
    <div class="album py-5">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
          {% for pic in page_obj %}
         
        <div class="col">
          <div class="card shadow-sm">
              {% if pic.thumb %}
                <img height="170px" src="/{{ pic.thumb }}" />
              {% else %}
                 <img height="170px" src="/media/{{ pic.pic}}" />
              {% endif %}
            

            <div class="card-body">
              <p class="card-text">{{ pic.body|truncatewords_html:30 }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{{ pic.get_absolute_url }}">View</a></button>
                </div>
                  {% for tag in pic.tags.all|slice:'3' %}
                  <a href="{% url 'vcars:tagged_index' tag.slug %}"><span class="badge text-bg-secondary">{{ tag.name}}</span></a>
                    
                  {% endfor %}
              </div>
            </div>
          <div class="rating-buttons">
                    <button class="btn btn-sm btn-primary" data-pic="{{ pic.id }}" data-value="1">Лайк</button>
                    <button class="btn btn-sm btn-secondary" data-pic="{{ pic.id }}" data-value="-1">Дизлайк
                    </button>
                    <button class="btn btn-sm btn-secondary rating-sum">{{ pic.count_rating }}</button>
                </div>
          </div>
        
      </div>
              
          {% endfor %}
      </div>
    </div>
    {% include 'includes/pagination.html' %}
  </div>
    <script src={% static 'scripts/ratings.js' %}></script>
{% endblock %}

templates/vcars/pic_detail.html
{% extends 'vcars/base.html' %}
{% load static %}

{% block content %}
    {% include 'includes/successful_pic_addition.html' %}
    <div class="pic-detail">
        <h1 class="pic-name">{{ pic.name }}</h1>
        <img src="/media/{{ pic.pic }}" class="img-fluid mx-auto d-block">
        <p class="text-center fw-medium fs-4">
            {{ pic.body }}
            <br>
            {% for tag in pic.tags.all %}
                <a href="{% url 'vcars:tagged_index' tag.slug %}"><span
                        class="badge text-bg-secondary">{{ tag.name }}</span></a>

            {% endfor %}
        </p>

    </div>
    <div class="comments">
    <div class="col-md-8 card mb-4  mt-3 ">
    <div class="card-body" id="comments-body">
       <h2 id="comments-count">{{ comments.count }} comments</h2>
        {% for comment in comments %}
            {% include 'includes/comment.html' %}
        {% endfor %}
      </div> 
    </div>
    </div>
    <div class="comment-form">
    <form hx-post="{{pic.get_absolute_url}}" hx-target="#comments-body" hx-swap="beforeend">
        {% csrf_token %}
        {{ form.as_div }}
        <input type="submit" class="btn btn-primary  btn-lg">
    </form>
    </div>
    <script src="{% static 'scripts/comments_counter.js' %}"></script>
{% endblock %}

templates/vcars/post_pic.html
{% extends 'vcars/base.html' %}
{% block content %}
    <div class="form-container">
    <form method="post" enctype="multipart/form-data" class="form-pic">
        {{ form.as_div }}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary btn-lg" value="Добавить картинку">
    </form>
    </div>
{% endblock %}